# This is NOT a OS shell script, but a Karaf script
# To execute it, open a Karaf shell for your container and type: source scripts/<This script's name>

RMI_Registry_Port=1104
RMI_Server_Port=44449
HTTP_Port=8045
HTTPS_Port=9006
SSH_Port=8106
COMMAND_SERVER_PORT=8023
FILE_SERVER_PORT=8024
MONITORING_PORT=8911
PROCESS_MESSAGE_PORT=8578
MS_PORT_RANGE_START=5110
MS_LOG_COLLECTION_PORT=7792
OSGI_LOG_COLLECTION_PORT=7793
ESB_RMI_SERVER_HOST=localhost
ESB_RMI_SERVER_PORT=44446
ESB_RMI_REGISTRY_SERVER=localhost
ESB_RMI_REGISTRY_PORT=1101
OMC_Port=9502

source scripts/configKarafContainer.sh $RMI_Registry_Port $RMI_Server_Port $HTTP_Port $HTTPS_Port $SSH_Port $COMMAND_SERVER_PORT $FILE_SERVER_PORT $MONITORING_PORT $PROCESS_MESSAGE_PORT $MS_PORT_RANGE_START $MS_LOG_COLLECTION_PORT $OSGI_LOG_COLLECTION_PORT $ESB_RMI_SERVER_HOST $ESB_RMI_SERVER_PORT $ESB_RMI_REGISTRY_SERVER $ESB_RMI_REGISTRY_PORT $OMC_Port
