# This is NOT a OS shell script, but a Karaf script
# To execute it, open a Karaf shell for your container and type: source scripts/<This script's name>

RMI_Registry_Port=1102
RMI_Server_Port=44447
HTTP_Port=8043
HTTPS_Port=9004
SSH_Port=8104
COMMAND_SERVER_PORT=8003
FILE_SERVER_PORT=8004
MONITORING_PORT=8891
PROCESS_MESSAGE_PORT=8558
MS_PORT_RANGE_START=5070
MS_LOG_COLLECTION_PORT=7788
OSGI_LOG_COLLECTION_PORT=7789
ESB_RMI_SERVER_HOST=localhost
ESB_RMI_SERVER_PORT=44444
ESB_RMI_REGISTRY_SERVER=localhost
ESB_RMI_REGISTRY_PORT=1099
OMC_Port=9500

source scripts/configKarafContainer.sh $RMI_Registry_Port $RMI_Server_Port $HTTP_Port $HTTPS_Port $SSH_Port $COMMAND_SERVER_PORT $FILE_SERVER_PORT $MONITORING_PORT $PROCESS_MESSAGE_PORT $MS_PORT_RANGE_START $MS_LOG_COLLECTION_PORT $OSGI_LOG_COLLECTION_PORT $ESB_RMI_SERVER_HOST $ESB_RMI_SERVER_PORT $ESB_RMI_REGISTRY_SERVER $ESB_RMI_REGISTRY_PORT $OMC_Port
